// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApKVQcjUOQU1JSLIiRR8FgQ7Gy25agNLE',
    appId: '1:354857769646:web:895963d453fbe89672eb3f',
    messagingSenderId: '354857769646',
    projectId: 'ititraining-2d5e8',
    authDomain: 'ititraining-2d5e8.firebaseapp.com',
    storageBucket: 'ititraining-2d5e8.appspot.com',
    measurementId: 'G-ZST7LXGNHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW3ZqUD1kdk8gG1pvtW6a6x_8xWVHrNsM',
    appId: '1:354857769646:android:d767a03043f7153772eb3f',
    messagingSenderId: '354857769646',
    projectId: 'ititraining-2d5e8',
    storageBucket: 'ititraining-2d5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKo79UwoLXK7UTj1nJvlWlalHTIiH07eQ',
    appId: '1:354857769646:ios:fcbb686a10a8329572eb3f',
    messagingSenderId: '354857769646',
    projectId: 'ititraining-2d5e8',
    storageBucket: 'ititraining-2d5e8.appspot.com',
    iosClientId: '354857769646-f0ljr2njhgqda9b6qnnr5umqtbv9iu3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
